### ISSUE TITLE
Latency issues and inquiry about backing

### ISSUE THREAD

**Issue by Zwilgmeyer** [nxvvvv/safe-exam-browser-bypass#13]
Hi. Thank you for your tremendous work. Is there any way to back your work financially?

Also I wanted to bend your ear about some latency issues with vmware when inside a SEB session. Last time I had 5 second latency. Any way to improve this? Running on a 16 gig ddr5 laptop with 6800h 8 core 16t cpu running at performance mode.. The instance is allocated 60 gig of NVMe storage, 8 threads and 8 gigs of ram.

**Comment by nxvvvv** [comment]
Hey! It's flattering to hear you're thinking about backing my work. I'm setting up something like PayPal for contributions, so I'll let you know when that's ready.

I'll surely check what can be done on the VMware latency in SEB sessions! I'm on it with SEB 3.6 and putting together some ready-to-go images for VMware/VirtualBox, maybe Hyper-V. They'll have all the patches and stuff you need. Just import, and tweak the storage and RAM, and you should be good to go.

Thanks for hanging in there while I sort this out. Updates will be coming soon, and your support means a lot! :)

**Comment by lathianamc** [comment]
I have also noticed a similar behaviour exactly one year ago. I gave the VM almost full access to my host's power processing, and everything ran smoothly I could even play some games via the VM, so I was sure that in terms of CPU/RAM etc., the VM could perform smoothly. Once the exam session started, everything was VERY slow, the mouse was lagging the keyboard input was lagging, thankfully the exam was just 40 multiple choice and most of the calculations could be done in Excel on my host machine or with pen and paper, but if it was required to deliver a Word document, it would take forever. The Uni uses its own SEB server and monitors the monitor and the camera at the same time.

**Comment by dritogdraUIS** [comment]
@nxvvvv Great. Keep me posted.

No worries. I had mine in december. Im good for a few months.

Terrific. That sounds like a good idea. Thank you for your work and good luck on your exams

@lathianamc Im glad you were able to resolve it. Any idea why the monitoring slows the system down so much? Any idea what could be done to offset it? If the VM has enough resources then surely it should be able to carry close to the same workloads as the host machine, shouldn't it?

Normally the lag is minor. 1 second delay at most for sessions with up to three separate 1000 word body of text tasks. But for the latest one with several smaller tasks requiring both full text answers and the drawing of figures, the whole system grinded to nearly a halt. Had to write everything in a wordpad and then paste it in. With the newest version of SEB it is no longer possible to copy paste from the host machine either. So if this happens again in the future, one would have to forfeit the entire session and do the whole thing over on a different date without using a VM.

Does it matter what network one is connected to? For security reasons, tethering through phone has been used previously. Anything gained or lost in security or speed by using the institutions public network? And is 16gigs of ram for the host sytem enough? How much ram should the host machine and the VM have for optimal performance? How many threads and how much storage? Is any chip manufacturer superior to the other for this type of workload? (AMD or intel)

**Comment by lathianamc** [comment]
@dritogdraUIS I couldn't resolve it, it just happened that my next exams were with a physical presence, thankfully I aced. Now, for this semester they announced to us that our exams will be with the closed book distance proctor method, and so far they have not explained to us how exactly they will conduct them and if they will use SEB at all or if there will be another solution. Most likely they will demand two cameras, one from the computer to watch us and one from a smartphone to watch our workspace, which, essentially eliminates the possibility of having SEB running in VM in the first place since you'll be monitored from your phone's camera on what you have on your desk and what is shown on your screen.

Regarding lag, I have no idea as to why it happened. I'm on Ethernet always, and my connection is fast and stable, at that time I had a 9700k CPU, RX 580 Pulse GPU and 32GB DDR4 RAM, now I have 64GB 6000MT/s DDR5 RAM, 13700k CPU, and dual RX 6600 XT GPU. Once the session started, it brought my PC down to its knees and once the session ended, everything went back to normal again. My fans weren't spinning like hell or anything like it, matter of fact, the PC resources used were not that high, but, for some unknown reason, the experience was like if you were to run Cyberpunk in a 90s PC (hypothetically). If they decide to use SEB this year, and if I see a benefit of my running the SEB via the VM (if they don't decide to use the second camera), then I'll report back. One more thing that I noticed is that on macOS, Parallels works MUCH better than VMWare, like MUCH MUCH better in terms of performance, but, unfortunately, with parallels I couldn't mask the fact that I'm running SEB via VM, therefore SEB was not working.

**Comment by nxvvvv** [comment]
![Screenshot (2)](https://github.com/nxvvvv/safe-exam-browser-bypass/assets/34748927/27cfbb69-76d4-4ad0-a3e6-034175ff604b)

I think I solved your issue. Now it's working perfectly fine. Latency is okay even on my potato so it must work perfectly on yours. I'll be uploading this pre-built VM on the releases soon

**Comment by dritogdraUIS** [comment]
@nxvvvv Terrific. Thank you. On another note. Did you happen to find a way to bypass the closed clipboard system? One of the real benefits of the old solution was the ability to copy/paste in pre-made templates to save time. A lot of the time saving is sadly lost with this change.

@lathianamc good luck on your new school policy. I hope you find a solution. The institution I am acquinted with always has in-person exams at the institution. But in my experience nobody neither look at recordings or bother to check what you are actually doing during the exam. The guards just march back and forth being bored and look for people requiring bathroom breaks. Guessing you could get by with some sleight of hand either way.

**Comment by nxvvvv** [comment]
Yea I'm currently working on that.

**Comment by nxvvvv** [comment]
@lathianamc @dritogdraUIS Here is the link to the SEB Bypass Prebuilt VM. I hope it works fine for everyone.

[Direct Link](https://archive.org/download/sebby/SEB%20Bypass.7z)
[Torrent](https://archive.org/download/sebby/sebby_archive.torrent) - Faster

**Comment by lathianamc** [comment]
Thanks for the VM! I'm going to test it out! By the way, our university decided to use ProctorU for the exams instead of SEB... :/

**Comment by Zwilgmeyer** [comment]
Thank you @nxvvvv. What is the password to the VM? Says its enctrypted. And how much ram and threads do I need to run it optimally? Anything to be gained from upgrading to a 32gb ram pc and giving the VM a proper 16gb?

@lathianamc Sorry to hear that man. Not familiar with it. Hope you find a workaround. Could be a VM works with that one too. With some luck they haven't put in place any safeguards against it.

**Comment by nxvvvv** [comment]
>What is the password to the VM? Says its enctrypted

The TPM password is `nxvvvvvv`.

>And how much ram and threads do I need to run it optimally? Anything to be gained from upgrading to a 32gb ram pc and giving the VM a proper 16gb?

I mean it worked well with 6Gigs of RAM for me since I have only 8 gigs. I mean just extract it to a new folder, import it in VMware and try messing with it for a while, like changing the RAM and other stuff and yea check which works the best for you. 

The Windows here is like an even more stripped up version of the latest Tiny Windows 11 so yea it's like Ultralight. I removed WinDefender so that's a huge level up.

**Comment by Zwilgmeyer** [comment]
@nxvvvv Its looking fantastic. Loving the login screen😄 And the convenience of everything being set up already is awesome. Going to have to wait until my inst. upgrades to SEB .6 to try it out properly, but the VM is terrific. Thank you so much. And thanks for the tip. Guessing allocating 8gb should be alright then.

**Comment by nxvvvv** [comment]
> @nxvvvv Its looking fantastic. Loving the login screen😄 And the convenience of everything being set up already is awesome. Going to have to wait until my inst. upgrades to SEB .6 to try it out properly, but the VM is terrific. Thank you so much. And thanks for the tip. Guessing allocating 8gb should be alright then.

Ummmmm the SEB I've included there is already 3.6.0.633 with the patches.

And you're welcome. The VM took a bit of time to make and compressing it into 4 GiB in my PC is a pain. But yea it was definitely worth the pain. 🙂

**Comment by Zwilgmeyer** [comment]
@nxvvvv It is. But my institution hasn't implemented 3.6 yet. They are still on 3.5. So the site is asking me to replace the installed one with the old 3.5 in order to work. But no matter. By the time I need it, likely they will be on 3.6 too.

I noticed the sponsorship option. Is that ypur preferred way of receiving support? I want to make sure any support I give doesn't cut in a third party unneccessarily. I prefer you get any money I send your way

**Comment by nxvvvv** [comment]
> I noticed the sponsorship option. Is that ypur preferred way of receiving support? I want to make sure any support I give doesn't cut in a third party unneccessarily. I prefer you get any money I send your way

Hey, I appreciate your thoughtfulness to support once again, but this is probably the best way other than Wire Transfer (I wouldn't prefer it that much since I'll have to share a lot of details) and Crypto(since they charge almost 50% for converting it to Indian Rupees). And sadly PayPal doesn't support receiving payments in India. So yea, GitHub support all the way at the moment.

Best of luck on your exams.

**Comment by nxvvvv** [comment]
> Thanks for the VM! I'm going to test it out! By the way, our university decided to use ProctorU for the exams instead of SEB... :/ 

Actually that's ok right. You can run a windows vm with a browser and then search the question up 

"What the browser extension does and doesn’t do  "
 https://www.uts.edu.au/current-students/managing-your-course/classes-and-assessment/exams/online-exams/how-download-and-set-proctoru-browser-extension#:~:text=selecting%20%27Remove%20extension.%27-,What%20the%20browser%20extension%20does%20and%20doesn%E2%80%99t%20do%C2%A0%C2%A0,-What%20does%20the

**Comment by the1n1ly** [comment]
Sorry for the unrelated question, but this seems the most active thread to ask this and hopefully get a reply today. I've read that Moodle has a browser key when performing exams to detect if the SEB installation is alterred. Does this bypass work with moodle?

**Comment by nxvvvv** [comment]
@the1n1ly Hey, I actually don't think Moodle has something like that. It'd be great if you provide where you got that information so that I can dig more into it.

By the way, I reply to almost every single issue or discussion. So yea you can create a new **Issue** and I'll surely check that

**Comment by Zwilgmeyer** [comment]
@nxvvvv Thank you man. Sent a little token of my appreciation. Hope the thing works and you get it safely. if not, do let me know.

**Comment by nxvvvv** [comment]
@dritogdraUIS Hey there! I got the token loud and clear, and it's beyond awesome. I'm truly touched. Thanks a million!!

**Comment by Zwilgmeyer** [comment]
You're welcome man. It is most deserved. I'll be chipping in a little bit every month. I hope others will follow suit..

**Comment by nxvvvv** [comment]
That's so nice of you man. I appreciate it a lot. This means a lot to me. 
 
Don't donate the amount anonymously. Let everyone know that you're helping me with this project. :)

**Comment by Zwilgmeyer** [comment]
You are right. It should be visible to help get the ball rolling and maybe bring in more backers.
